version: 2
jobs:
  build:
    docker:
      - image: circleci/node:latest
    working_directory: ~/repo
    steps:
      - checkout
      - restore_cache:
          keys:
            - gatsby-theme-moltin-{{ checksum "package.json" }}
            # fallback to using the latest cache if no exact match is found
            - gatsby-theme-moltin-
      - run: yarn
      - save_cache:
          paths:
            - node_modules
          key: gatsby-theme-moltin-{{ checksum "package.json" }}
workflows:
  version: 2
  build_release:
    jobs:
      - build
